/* tslint:disable */
/* eslint-disable */
/**
 * ServePOS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MenuItem,
  MenuItemInsertInformation,
  MenuItemUpdateInformation,
} from '../models/index';
import {
    MenuItemFromJSON,
    MenuItemToJSON,
    MenuItemInsertInformationFromJSON,
    MenuItemInsertInformationToJSON,
    MenuItemUpdateInformationFromJSON,
    MenuItemUpdateInformationToJSON,
} from '../models/index';

export interface MenuItemIdDeleteRequest {
    id: number;
}

export interface MenuItemIdPushSortOrderPutRequest {
    id: number;
    down?: boolean;
}

export interface MenuItemIdPutRequest {
    id: number;
    menuItemUpdateInformation?: Omit<MenuItemUpdateInformation, 'isActive'>;
}

export interface MenuItemPostRequest {
    menuItemInsertInformation?: MenuItemInsertInformation;
}

/**
 * 
 */
export class MenuApi extends runtime.BaseAPI {

    /**
     * Creates request options for menuGet without sending the request
     */
    async menuGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/menu`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async menuGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MenuItem>>> {
        const requestOptions = await this.menuGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MenuItemFromJSON));
    }

    /**
     */
    async menuGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MenuItem>> {
        const response = await this.menuGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for menuItemIdDelete without sending the request
     */
    async menuItemIdDeleteRequestOpts(requestParameters: MenuItemIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling menuItemIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/menu/item/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async menuItemIdDeleteRaw(requestParameters: MenuItemIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.menuItemIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async menuItemIdDelete(requestParameters: MenuItemIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.menuItemIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for menuItemIdPushSortOrderPut without sending the request
     */
    async menuItemIdPushSortOrderPutRequestOpts(requestParameters: MenuItemIdPushSortOrderPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling menuItemIdPushSortOrderPut().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['down'] != null) {
            queryParameters['down'] = requestParameters['down'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/menu/item/{id}/pushSortOrder`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async menuItemIdPushSortOrderPutRaw(requestParameters: MenuItemIdPushSortOrderPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.menuItemIdPushSortOrderPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async menuItemIdPushSortOrderPut(requestParameters: MenuItemIdPushSortOrderPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.menuItemIdPushSortOrderPutRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for menuItemIdPut without sending the request
     */
    async menuItemIdPutRequestOpts(requestParameters: MenuItemIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling menuItemIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/menu/item/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MenuItemUpdateInformationToJSON(requestParameters['menuItemUpdateInformation']),
        };
    }

    /**
     */
    async menuItemIdPutRaw(requestParameters: MenuItemIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.menuItemIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async menuItemIdPut(requestParameters: MenuItemIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.menuItemIdPutRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for menuItemPost without sending the request
     */
    async menuItemPostRequestOpts(requestParameters: MenuItemPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/menu/item`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MenuItemInsertInformationToJSON(requestParameters['menuItemInsertInformation']),
        };
    }

    /**
     */
    async menuItemPostRaw(requestParameters: MenuItemPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.menuItemPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async menuItemPost(requestParameters: MenuItemPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.menuItemPostRaw(requestParameters, initOverrides);
    }

}
