/* tslint:disable */
/* eslint-disable */
/**
 * ServePOS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  StaffInfo,
  StaffUpsert,
} from '../models/index';
import {
    StaffInfoFromJSON,
    StaffInfoToJSON,
    StaffUpsertFromJSON,
    StaffUpsertToJSON,
} from '../models/index';

export interface StaffIdPutRequest {
    id: number;
    staffUpsert?: StaffUpsert;
}

export interface StaffPostRequest {
    staffUpsert?: StaffUpsert;
}

/**
 * 
 */
export class StaffApi extends runtime.BaseAPI {

    /**
     * Creates request options for staffGet without sending the request
     */
    async staffGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/staff`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async staffGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<StaffInfo>>> {
        const requestOptions = await this.staffGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(StaffInfoFromJSON));
    }

    /**
     */
    async staffGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<StaffInfo>> {
        const response = await this.staffGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for staffIdPut without sending the request
     */
    async staffIdPutRequestOpts(requestParameters: StaffIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling staffIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/staff/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: StaffUpsertToJSON(requestParameters['staffUpsert']),
        };
    }

    /**
     */
    async staffIdPutRaw(requestParameters: StaffIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.staffIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async staffIdPut(requestParameters: StaffIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.staffIdPutRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for staffPost without sending the request
     */
    async staffPostRequestOpts(requestParameters: StaffPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/staff`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StaffUpsertToJSON(requestParameters['staffUpsert']),
        };
    }

    /**
     */
    async staffPostRaw(requestParameters: StaffPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.staffPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async staffPost(requestParameters: StaffPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.staffPostRaw(requestParameters, initOverrides);
    }

}
