/* tslint:disable */
/* eslint-disable */
/**
 * ServePOS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MenuItemInsertInformation
 */
export interface MenuItemInsertInformation {
    /**
     * 
     * @type {string}
     * @memberof MenuItemInsertInformation
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof MenuItemInsertInformation
     */
    shortName: string | null;
    /**
     * 
     * @type {number}
     * @memberof MenuItemInsertInformation
     */
    price: number;
    /**
     * 
     * @type {MenuItemInsertInformationTypeEnum}
     * @memberof MenuItemInsertInformation
     */
    type: MenuItemInsertInformationTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof MenuItemInsertInformation
     */
    availableQuantity?: number | null;
}


/**
 * @export
 */
export const MenuItemInsertInformationTypeEnum = {
    Drink: 'Drink',
    Food: 'Food',
    Dessert: 'Dessert',
    Special: 'Special'
} as const;
export type MenuItemInsertInformationTypeEnum = typeof MenuItemInsertInformationTypeEnum[keyof typeof MenuItemInsertInformationTypeEnum];


/**
 * Check if a given object implements the MenuItemInsertInformation interface.
 */
export function instanceOfMenuItemInsertInformation(value: object): value is MenuItemInsertInformation {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('shortName' in value) || value['shortName'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function MenuItemInsertInformationFromJSON(json: any): MenuItemInsertInformation {
    return MenuItemInsertInformationFromJSONTyped(json, false);
}

export function MenuItemInsertInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): MenuItemInsertInformation {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'shortName': json['shortName'],
        'price': json['price'],
        'type': json['type'],
        'availableQuantity': json['availableQuantity'] == null ? undefined : json['availableQuantity'],
    };
}

export function MenuItemInsertInformationToJSON(json: any): MenuItemInsertInformation {
    return MenuItemInsertInformationToJSONTyped(json, false);
}

export function MenuItemInsertInformationToJSONTyped(value?: MenuItemInsertInformation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'shortName': value['shortName'],
        'price': value['price'],
        'type': value['type'],
        'availableQuantity': value['availableQuantity'],
    };
}

