/* tslint:disable */
/* eslint-disable */
/**
 * ServePOS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MenuItemUpdateInformation
 */
export interface MenuItemUpdateInformation {
    /**
     * 
     * @type {string}
     * @memberof MenuItemUpdateInformation
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof MenuItemUpdateInformation
     */
    shortName: string | null;
    /**
     * 
     * @type {number}
     * @memberof MenuItemUpdateInformation
     */
    price: number;
    /**
     * 
     * @type {MenuItemUpdateInformationTypeEnum}
     * @memberof MenuItemUpdateInformation
     */
    type: MenuItemUpdateInformationTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof MenuItemUpdateInformation
     */
    availableQuantity?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof MenuItemUpdateInformation
     */
    readonly isActive?: boolean;
}


/**
 * @export
 */
export const MenuItemUpdateInformationTypeEnum = {
    Drink: 'Drink',
    Food: 'Food',
    Dessert: 'Dessert',
    Special: 'Special'
} as const;
export type MenuItemUpdateInformationTypeEnum = typeof MenuItemUpdateInformationTypeEnum[keyof typeof MenuItemUpdateInformationTypeEnum];


/**
 * Check if a given object implements the MenuItemUpdateInformation interface.
 */
export function instanceOfMenuItemUpdateInformation(value: object): value is MenuItemUpdateInformation {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('shortName' in value) || value['shortName'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function MenuItemUpdateInformationFromJSON(json: any): MenuItemUpdateInformation {
    return MenuItemUpdateInformationFromJSONTyped(json, false);
}

export function MenuItemUpdateInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): MenuItemUpdateInformation {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'shortName': json['shortName'],
        'price': json['price'],
        'type': json['type'],
        'availableQuantity': json['availableQuantity'] == null ? undefined : json['availableQuantity'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
    };
}

export function MenuItemUpdateInformationToJSON(json: any): MenuItemUpdateInformation {
    return MenuItemUpdateInformationToJSONTyped(json, false);
}

export function MenuItemUpdateInformationToJSONTyped(value?: Omit<MenuItemUpdateInformation, 'isActive'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'shortName': value['shortName'],
        'price': value['price'],
        'type': value['type'],
        'availableQuantity': value['availableQuantity'],
    };
}

