/* tslint:disable */
/* eslint-disable */
/**
 * ServePOS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderItem } from './OrderItem';
import {
    OrderItemFromJSON,
    OrderItemFromJSONTyped,
    OrderItemToJSON,
    OrderItemToJSONTyped,
} from './OrderItem';

/**
 * 
 * @export
 * @interface OrderInformation
 */
export interface OrderInformation {
    /**
     * 
     * @type {number}
     * @memberof OrderInformation
     */
    staffId: number;
    /**
     * 
     * @type {string}
     * @memberof OrderInformation
     */
    tableId: string | null;
    /**
     * 
     * @type {Array<OrderItem>}
     * @memberof OrderInformation
     */
    items: Array<OrderItem> | null;
}

/**
 * Check if a given object implements the OrderInformation interface.
 */
export function instanceOfOrderInformation(value: object): value is OrderInformation {
    if (!('staffId' in value) || value['staffId'] === undefined) return false;
    if (!('tableId' in value) || value['tableId'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function OrderInformationFromJSON(json: any): OrderInformation {
    return OrderInformationFromJSONTyped(json, false);
}

export function OrderInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderInformation {
    if (json == null) {
        return json;
    }
    return {
        
        'staffId': json['staffId'],
        'tableId': json['tableId'],
        'items': (json['items'] == null ? null : (json['items'] as Array<any>).map(OrderItemFromJSON)),
    };
}

export function OrderInformationToJSON(json: any): OrderInformation {
    return OrderInformationToJSONTyped(json, false);
}

export function OrderInformationToJSONTyped(value?: OrderInformation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'staffId': value['staffId'],
        'tableId': value['tableId'],
        'items': (value['items'] == null ? null : (value['items'] as Array<any>).map(OrderItemToJSON)),
    };
}

