/* tslint:disable */
/* eslint-disable */
/**
 * ServePOS.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StaffUpsert
 */
export interface StaffUpsert {
    /**
     * 
     * @type {string}
     * @memberof StaffUpsert
     */
    name: string | null;
}

/**
 * Check if a given object implements the StaffUpsert interface.
 */
export function instanceOfStaffUpsert(value: object): value is StaffUpsert {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function StaffUpsertFromJSON(json: any): StaffUpsert {
    return StaffUpsertFromJSONTyped(json, false);
}

export function StaffUpsertFromJSONTyped(json: any, ignoreDiscriminator: boolean): StaffUpsert {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function StaffUpsertToJSON(json: any): StaffUpsert {
    return StaffUpsertToJSONTyped(json, false);
}

export function StaffUpsertToJSONTyped(value?: StaffUpsert | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

